baseURL = "https://masa10223.github.io/"
title = "Masato Tsutsumi"
# Keep Japanese at root ("/") and English at "/en/"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false


[pagination]
  pagerSize = 10

# Speed up Hugo Blox image processing in GitHub Actions
[caches]
  [caches.images]
    dir = ":cacheDir/images"

[module]
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5"

[params]
  description = "Postdoctoral researcher at Hiroshima University. Deep learning for morphology and social stress modeling."
  dateFormat = "2025-08-08"
  
  # Analytics Options
  [params.analytics]
    # Google Analytics 4
    google_analytics = "G-XXXXXXXXXX"  # あなたの測定IDに置き換えてください
    
    # Plausible Analytics (プライバシー重視)
    # plausible_domain = "masa10223.github.io"
    # plausible_script = "https://plausible.io/js/script.js"
  
  # UI Options
  show_visitor_counter = false  # 訪問者カウンターを表示するかどうか

[markup]
  [markup.goldmark.renderer]
    unsafe = true

# hugo.toml に追加（既に [security] があるならマージして OK）
[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']

  [security.funcs]
    # ここに ^WC_ を足すのがポイント
    getenv = ['^HUGO_', '^CI$', '^WC_']

  [security.goTemplates]
    AllowActionJSTmpl = false

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
