[[main]]
  name = "ホーム"
  url = "/ja/home/"
  weight = 10
[[main]]
  name = "プロジェクト"
  url = "/ja/#projects"
  weight = 20
[[main]]
  name = "業績"
  url = "/ja/#publications"
  weight = 30
[[main]]
  name = "CV"
  url = "/ja/cv/"
  weight = 35
[[main]]
  name = "連絡先"
  url = "/ja/#contact"
  weight = 40