[[main]]
name   = "ホーム"
url = "/ja/#about/"
weight = 1

[[main]]
name   = "プロジェクト"
url = "/ja/project/"
weight = 20

[[main]]
name   = "研究業績"
url = "/ja/publication/"
weight = 30

[[main]]
name   = "CV"
url = "/ja/cv/"
weight = 40

# 連絡先は Home ページ内のウィジェットに飛ばしたいならアンカーを使う
[[main]]
name   = "連絡先"
url = "/ja/#contact"
weight = 50