[[main]]
  name = "ホーム"
  pageRef = "ja/home"     # ← これ！
  weight = 1

[[main]]
  name   = "プロジェクト"
  pageRef = "project"  # セクションに飛ぶ
  weight = 20

[[main]]
  name   = "研究業績"
  pageRef = "publication"
  weight = 30

[[main]]
  name   = "CV"
  pageRef = "cv"
  weight = 40

[[main]]
  name   = "連絡先"
  pageRef = "home/contact"  # ホーム配下のウィジェットにもOK
  weight = 50
