[[main]]
name   = "ホーム"
url = "/ja/"
weight = 1

[[main]]
name   = "プロジェクト"
pageRef = "ja/project"
weight = 20

[[main]]
name   = "研究業績"
pageRef = "ja/publication"
weight = 30

[[main]]
name   = "CV"
pageRef = "ja/cv"
weight = 40

# 連絡先は Home ページ内のウィジェットに飛ばしたいならアンカーを使う
[[main]]
name   = "連絡先"
pageRef = "ja/home"
weight = 50