# config/_default/params.toml


[social]
  github = "masa10223"
  email = "tsutsumi.masato.s1@f.mail.nagoya-u.ac.jp"
  location = "Showa-ku, Nagoya, Aichi, Japan"
  org = "Nagoya University"

[appearance]
  mode = "dark"
  color = "blue"

[pagination]
  pagerSize = 10

[license]
  enable = true
  text = "CC BY-NC-ND 4.0"
  url  = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[footer]
  copyright = "© 2025 Masato Tsutsumi"
