[footer]
  copyright = "© 2025 Masato Tsutsumi"
  license = "CC BY-NC-ND 4.0"

[social]
  github = "masa10223"
  email = "tsutsumi.masato.s1@f.mail.nagoya-u.ac.jp"
  location = "Showa-ku, Nagoya, Aichi, Japan"
  org = "Nagoya University"

[appearance]
# 既定の見た目（light / dark / system）
mode = "dark"
# カラーテーマ（blue / indigo / teal...）
color = "blue"