# config/_default/params.toml


[social]
  github = "masa10223"
  email = "tsutsumi.masato.s1@f.mail.nagoya-u.ac.jp"
  location = "Showa-ku, Nagoya, Aichi, Japan"
  org = "Nagoya University"

[appearance]
  # 既定の見た目（light / dark / system）
  mode = "dark"
  # カラーテーマ（blue / indigo / teal...）
  color = "blue"